name: Archive Artifacts

on: workflow_dispatch

jobs:
  artifact-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile Java
        run: javac Hello.java

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-class
          path: Hello.class
