name: Java Build

on: workflow_dispatch

jobs:
  java-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compile Java file
        run: javac Hello.java

      - name: Run Java program
        run: java Hello
