name: Post Build Actions

on: workflow_dispatch

jobs:
  post-job:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: echo "Building..."

      - name: Success Message
        if: success()
        run: echo "BUILD SUCCESSFUL ✅"

      - name: Failure Message
        if: failure()
        run: echo "BUILD FAILED ❌"
